brokers = "${KAFKA_BROKERS}"
applicationIdPrefix = "${KAFKA_STREAMS_APPLICATION_ID}-"

[authentication]
keystorePath = "${KAFKA_KEYSTORE_PATH}"
truststorePath = "${KAFKA_TRUSTSTORE_PATH}"
credstorePassword = "${KAFKA_CREDSTORE_PASSWORD}"

[schemaRegistry]
url = "${KAFKA_SCHEMA_REGISTRY}"
username = "${KAFKA_SCHEMA_REGISTRY_USER}"
password = "${KAFKA_SCHEMA_REGISTRY_PASSWORD}"