### SERVICES ###
services:
  database:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=arbeidssoekerregisteretapioppslag
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - postgres

### VOLUMES ###
volumes:
  postgres:
    name: postgres

### NETWORKS ###
networks:
  mocks:
    name: postgres
