### SERVICES ###
services:
  # OTEL Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    depends_on:
      - tempo
    command:
      - --config=/etc/otel-collector.yaml
  #  ports:
  #    - "4317:4317"
  #    - "55678:55678"
  #    - "55679:55679"
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector.yaml
    networks:
      - grafana

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "3030:3000"
    volumes:
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-data:/var/lib/grafana
    networks:
      - grafana

  # Grafana Tempo
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command:
      - -config.file=/etc/tempo.yaml
  #  ports:
  #    - "14268:14268" # jaeger ingest
  #    - "3200:3200"   # tempo
  #    - "9095:9095"   # tempo grpc
  #    - "4317:4317"   # otlp grpc
  #    - "4318:4318"   # otlp http
  #    - "9411:9411"   # zipkin
    volumes:
      - ./config/grafana-tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    networks:
      - grafana

  # Grafana K6 Tracing
  #k6-tracing:
  #  image: ghcr.io/grafana/xk6-client-tracing:latest
  #  container_name: k6-tracing
  #  depends_on:
  #    - tempo
  #  environment:
  #    - ENDPOINT=tempo:4317
  #  networks:
  #    - grafana

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
  #  ports:
  #    - "9090:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
      - prometheus-data:/prometheus
    networks:
      - grafana

### VOLUMES ###
volumes:
  grafana-data:
    name: grafana-data
  tempo-data:
    name: tempo-data
  prometheus-data:
    name: prometheus-data

### NETWORKS ###
networks:
  grafana:
    name: grafana
