periodeTopic = "paw.arbeidssokerperioder-beta-v10"
opplysningerTopic = "paw.opplysninger-om-arbeidssoeker-beta-v10"
profileringTopic = "paw.arbeidssoker-profilering-beta-v10"
profileringGrunnlagTopic = "paw.arbeidssoeker-profilering-grunnlag-beta-v10"
applicationIdSuffix = "v6"
joiningStateStoreName = "joiningStateStore"