[topics]
opplysningerOmArbeidssoeker = "opplysninger-om-arbeidssoeker-beta-v1"
arbeidssokerperioder = "arbeidssokerperioder-beta-v1"
profilering = "arbeidssoker-profilering-beta-v1"
arena = "arbeidssoker-arena-beta-v1"