[[authProviders]]
name = "tokenx"
discoveryUrl = "${TOKEN_X_WELL_KNOWN_URL}"
tokenEndpointUrl = "${TOKEN_X_TOKEN_ENDPOINT}"
clientId = "${TOKEN_X_CLIENT_ID}"

[authProviders.requiredClaims]
map = ["acr=Level4", "acr=idporten-loa-high"]
combineWithOr = true

[azureM2M]
tokenEndpointUrl = "${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}"
clientId = "${AZURE_APP_CLIENT_ID}"

[kafka]
brokers = "${KAFKA_BROKERS}"
applicationIdPrefix = "${KAFKA_STREAMS_APPLICATION_ID}"

[kafka.schemaRegistry]
url = "${KAFKA_SCHEMA_REGISTRY}"

[kafkaProducer]
applicationIdSuffix = "${KAFKA_PRODUCER_APPLICATION_ID_SUFFIX}"

[kafkaStreams]
applicationIdSuffix = "${KAFKA_STREAMS_APPLICATION_ID_SUFFIX}"
periodeTopic = "${KAFKA_PAW_ARBEIDSSOKERPERIODER_TOPIC}"
rapporteringTopic = "${KAFKA_PAW_RAPPORTERING_TOPIC}"
siste14aVedtakTopic = "${KAFKA_PTO_SISTE_14A_VEDTAK_TOPIC}"
microfrontendTopic = "${KAFKA_TMS_MICROFRONTEND_TOPIC}"
periodeStoreName = "microfrontendTogglePeriodeStore"
siste14aVedtakPartitionCount = 6 # Må være samme antall partisjoner som periode-topic

[kafkaKeysClient]
url = "${KAFKA_KEY_URL}"
scope = "${KAFKA_KEY_SCOPE}"

[regler]
periodeTogglePunctuatorSchedule = "PT60S"
utsattDeaktiveringAvAiaMinSide = "PT10M"
fiksAktiveMicrofrontendsToggleSchedule = "PT60S"
fiksAktiveMicrofrontendsForPerioderEldreEnn = "2024-06-12T12:00:00"

[microfrontends]
aiaMinSide = "aia-min-side"
aiaBehovsvurdering = "aia-behovsvurdering"

[featureToggles]
enableKafkaStreams = ["docker"]
enablePeriodeTopology = ["docker"]
enable14aVedtakTopology = ["docker"]
enableFiksAktiveMicrofrontendsKafkaStreams = []
enableFiksAktiveMicrofrontendsPunctuator = []