[kafkaTopology]
periodeTopic = "${KAFKA_PAW_PERIODE_TOPIC}"
vedtakTopic = "${KAFKA_PTO_14A_VEDTAK_TOPIC}"
microfrontendTopic = "${KAFKA_TMS_MICROFRONTEND_TOPIC}"
toggleStoreName = "microfrontend-toggle"
varselStoreName = "microfrontend-varsel"
periodeToggleProcessor = "microfrontend-toggle-periode"

[kafkaKeys]
url = "http://paw-kafka-key-generator/api/v2/hentEllerOpprett"
scope = "${KAFKA_KEY_SCOPE}"

[regler]
periodeTogglePunctuatorSchedule = "PT6H"
utsattDeaktiveringAvAiaMinSide = "P21D"

[microfrontends]
aiaMinSide = "aia-min-side"
aiaBehovsvurdering = "aia-behovsvurdering"