[kafkaTopology]
periodeTopic = "${KAFKA_PAW_PERIODE_TOPIC}"
vedtakTopic = "${KAFKA_PTO_14A_VEDTAK_TOPIC}"
microfrontendTopic = "${KAFKA_TMS_MICROFRONTEND_TOPIC}"
toggleStoreName = "microfrontend-toggle"
varselStoreName = "microfrontend-varsel"
periodeToggleProcessor = "microfrontend-toggle-periode"

[regler]
periodeTogglePunctuatorSchedule = "PT5M" # Redusert tid i forbindelse med test
utsattDeaktiveringAvAiaMinSide = "PT10M" # Redusert tid i forbindelse med test

[microfrontends]
aiaMinSide = "aia-min-side"
aiaBehovsvurdering = "aia-behovsvurdering"