[kafkaTopology]
shutDownTimeout = "PT5S"
periodeStreamIdSuffix = "${KAFKA_ARBEIDSSOKERPERIODER_STREAM_ID_SUFFIX}"
siste14aVedtakStreamIdSuffix = "${KAFKA_SISTE_14A_VEDTAK_STREAM_ID_SUFFIX}"
periodeTopic = "${KAFKA_PAW_ARBEIDSSOKERPERIODER_TOPIC}"
beriket14aVedtakTopic = "${KAFKA_PAW_BERIKET_14A_VEDTAK_TOPIC}"
siste14aVedtakTopic = "${KAFKA_PTO_SISTE_14A_VEDTAK_TOPIC}"
microfrontendTopic = "${KAFKA_TMS_MICROFRONTEND_TOPIC}"
periodeStoreName = "microfrontendTogglePeriodeStore"
toggleProducerIdSuffix = "${KAFKA_TOGGLE_PRODUCER_ID_SUFFIX}"

[microfrontendToggle]
aiaMinSide = "aia-min-side"
aiaBehovsvurdering = "aia-behovsvurdering"
periodeTogglePunctuatorSchedule = "PT6H"
utsattDeaktiveringAvAiaMinSide = "P21D"
toggleSensitivitet = "${TOGGLE_SENSITIVITET}"
