[[authProviders]]
name = "tokenx"
discoveryUrl = "${TOKEN_X_WELL_KNOWN_URL}"
tokenEndpointUrl = "${TOKEN_X_TOKEN_ENDPOINT}"
clientId = "${TOKEN_X_CLIENT_ID}"

[authProviders.requiredClaims]
map = ["acr=Level4", "acr=idporten-loa-high"]
combineWithOr = true

[azureM2M]
tokenEndpointUrl = "${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}"
clientId = "${AZURE_APP_CLIENT_ID}"

[kafka]
brokers = "${KAFKA_BROKERS}"
applicationIdPrefix = "${KAFKA_STREAMS_APPLICATION_ID}"

[kafka.authentication]
keystorePath = "${KAFKA_KEYSTORE_PATH}"
truststorePath = "${KAFKA_TRUSTSTORE_PATH}"
credstorePassword = "${KAFKA_CREDSTORE_PASSWORD}"

[kafka.schemaRegistry]
url = "${KAFKA_SCHEMA_REGISTRY}"
username = "${KAFKA_SCHEMA_REGISTRY_USER}"
password = "${KAFKA_SCHEMA_REGISTRY_PASSWORD}"

[kafkaProducer]
applicationIdSuffix = "producer-v1"

[kafkaStreams]
applicationIdSuffix = "stream-v1"
periodeTopic = "paw.arbeidssokerperioder-v1"
siste14aVedtakTopic = "pto.siste-14a-vedtak-v1"
rapporteringTopic = "paw.rapportering-v1"
microfrontendTopic = "min-side.aapen-microfrontend-v1"
periodeStoreName = "microfrontendTogglePeriodeStore"
siste14aVedtakPartitionCount = 6 # Må være samme antall partisjoner som periode-topic

[kafkaKeysClient]
url = "${KAFKA_KEY_URL}"
scope = "${KAFKA_KEY_SCOPE}"

[pdlClient]
url = "${PDL_URL}"
scope = "${PDL_SCOPE}"

[regler]
periodeTogglePunctuatorSchedule = "PT1H"
utsattDeaktiveringAvAiaMinSide = "P21D"

[microfrontends]
aiaMinSide = "aia-min-side"
aiaBehovsvurdering = "aia-behovsvurdering"

[featureToggle]
enablePeriodeTopology = true
enable14aVedtakTopology = true