[[authProviders]]
name = "tokenx"
discoveryUrl = "${TOKEN_X_WELL_KNOWN_URL}"
tokenEndpointUrl = "${TOKEN_X_TOKEN_ENDPOINT}"
clientId = "${TOKEN_X_CLIENT_ID}"

[authProviders.claims]
map = ["acr=Level4", "acr=idporten-loa-high"]
combineWithOr = true

[[authProviders]]
name = "azure"
discoveryUrl = "${AZURE_APP_WELL_KNOWN_URL}"
tokenEndpointUrl = "${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}"
clientId = "${AZURE_APP_CLIENT_ID}"

[authProviders.claims]
map = ["NAVident"]

[azureM2M]
tokenEndpointUrl = "${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}"
clientId = "${AZURE_APP_CLIENT_ID}"

[poaoClientConfig]
url = "http://poao-tilgang.poao.svc.cluster.local"
scope = "api://${NAIS_CLUSTER_NAME}.poao.poao-tilgang/.default"

[kafka]
brokers = "${KAFKA_BROKERS}"
applicationIdPrefix = "${KAFKA_STREAMS_APPLICATION_ID}"

[kafka.authentication]
keystorePath = "${KAFKA_KEYSTORE_PATH}"
truststorePath = "${KAFKA_TRUSTSTORE_PATH}"
credstorePassword = "${KAFKA_CREDSTORE_PASSWORD}"

[kafka.schemaRegistry]
url = "${KAFKA_SCHEMA_REGISTRY}"
username = "${KAFKA_SCHEMA_REGISTRY_USER}"
password = "${KAFKA_SCHEMA_REGISTRY_PASSWORD}"

[kafkaProducer]
applicationIdSuffix = "producer-v1"

[kafkaStreams]
applicationIdSuffix = "stream-v1"
periodeTopic = "${KAFKA_PAW_PERIODE_TOPIC}"
vedtakTopic = "${KAFKA_PTO_14A_VEDTAK_TOPIC}"
microfrontendTopic = "${KAFKA_TMS_MICROFRONTEND_TOPIC}"
toggleStoreName = "microfrontend-toggle"
varselStoreName = "microfrontend-varsel"
periodeToggleProcessor = "microfrontend-toggle-periode"
rapporteringToggleProcessor = "microfrontend-toggle-rapportering"

[kafkaKeys]
url = "${KAFKA_KEY_URL}"
scope = "${KAFKA_KEY_SCOPE}"

[regler]
periodeTogglePunctuatorSchedule = "PT1H"
utsattDeaktiveringAvAiaMinSide = "P21D"

[microfrontends]
aiaMinSide = "aia-min-side"
aiaBehovsvurdering = "aia-behovsvurdering"