[[authProviders]]
name = "tokenx"
audiences = ["${TOKEN_X_CLIENT_ID}"]
discoveryUrl = "${TOKEN_X_WELL_KNOWN_URL}"

    [authProviders.requiredClaims]
    claims = ["acr=Level4", "acr=idporten-loa-high"]
    combineWithOr = true
