applicationIdSuffix = "release-v1"
[topics]
opplysningerOmArbeidssoeker = "paw.opplysninger-om-arbeidssoeker-v1"
arbeidssokerperioder = "paw.arbeidssokerperioder-v1"
profilering = "paw.arbeidssoker-profilering-v1"
arena = "paw.arbeidssoker-arena-v1"