[topics]
opplysningerOmArbeidssoeker = "paw.opplysninger-om-arbeidssoeker-beta-v7"
arbeidssokerperioder = "paw.arbeidssokerperioder-beta-v7"
profilering = "paw.arbeidssoker-profilering-beta-v2"
arena = "aw.arbeidssoker-arena-beta-v1"