applicationIdSuffix = "v2"
[topics]
opplysningerOmArbeidssoeker = "paw.opplysninger-om-arbeidssoeker-beta-v11"
arbeidssokerperioder = "paw.arbeidssokerperioder-beta-v11"
profilering = "paw.arbeidssoker-profilering-beta-v11"
arena = "paw.arbeidssoker-arena-beta-v11"