periodeTopic = "paw.arbeidssokerperioder-beta-v14"
opplysningerTopic = "paw.opplysninger-om-arbeidssoeker-beta-v14"
profileringTopic = "paw.arbeidssoker-profilering-beta-v14"
profileringGrunnlagTopic = "paw.arbeidssoeker-profilering-grunnlag-beta-v14"
applicationIdSuffix = "v13"
joiningStateStoreName = "joiningStateStore"