periodeTopic = "paw.arbeidssokerperioder-beta-v7"
opplysningerTopic = "paw.opplysninger-om-arbeidssoeker-beta-v7"
profileringTopic = "paw.arbeidssoker-profilering-beta-v2"
profileringGrunnlagTopic = "paw.arbeidssoeker-profilering-grunnlag-beta-v1"
applicationIdSuffix = "v2"
joiningStateStoreName = "joiningStateStore"