periodeTopic = "paw.arbeidssokerperioder-v1"
opplysningerTopic = "paw.opplysninger-om-arbeidssoeker-v1"
profileringTopic = "paw.arbeidssoker-profilering-beta-v15"
profileringGrunnlagTopic = "paw.arbeidssoeker-profilering-grunnlag-beta-v15"
applicationIdSuffix = "v15"
joiningStateStoreName = "joiningStateStore"