[topics]
opplysningerOmArbeidssoeker = "opplysninger-om-arbeidssoeker-beta-v9"
arbeidssokerperioder = "arbeidssokerperioder-beta-v9"
profilering = "arbeidssoker-profilering-beta-v3"
arena = "arbeidssoker-arena-beta-v1"