periodeTopic = "paw.arbeidssokerperioder-beta-v9"
opplysningerTopic = "paw.opplysninger-om-arbeidssoeker-beta-v9"
profileringTopic = "paw.arbeidssoker-profilering-beta-v3"
profileringGrunnlagTopic = "paw.arbeidssoeker-profilering-grunnlag-beta-v1"
applicationIdSuffix = "v3"
joiningStateStoreName = "joiningStateStore"