applicationIdSuffix = "v1"
[topics]
opplysningerOmArbeidssoeker = "paw.opplysninger-om-arbeidssoeker-beta-v10"
arbeidssokerperioder = "paw.arbeidssokerperioder-beta-v10"
profilering = "paw.arbeidssoker-profilering-beta-v10"
arena = "paw.arbeidssoker-arena-beta-v10"