applicationIdSuffix = "v4"
[topics]
opplysningerOmArbeidssoeker = "paw.opplysninger-om-arbeidssoeker-v1"
arbeidssokerperioder = "paw.arbeidssokerperioder-v1"
profilering = "paw.arbeidssoker-profilering-beta-v15"
arena = "paw.arbeidssoker-arena-beta-v15"