periodeTopic = "paw.arbeidssokerperioder-beta-v12"
opplysningerTopic = "paw.opplysninger-om-arbeidssoeker-beta-v12"
profileringTopic = "paw.arbeidssoker-profilering-beta-v12"
profileringGrunnlagTopic = "paw.arbeidssoeker-profilering-grunnlag-beta-v12"
applicationIdSuffix = "v12"
joiningStateStoreName = "joiningStateStore"