host = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_EKSTERNT_API_ARBEIDSSOEKERREGISTERETAPIEKSTERN_HOST}"
port = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_EKSTERNT_API_ARBEIDSSOEKERREGISTERETAPIEKSTERN_PORT}"
username = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_EKSTERNT_API_ARBEIDSSOEKERREGISTERETAPIEKSTERN_USERNAME}"
password = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_EKSTERNT_API_ARBEIDSSOEKERREGISTERETAPIEKSTERN_PASSWORD}"
database = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_EKSTERNT_API_ARBEIDSSOEKERREGISTERETAPIEKSTERN_DATABASE}"
