[[authProviders]]
name = "maskinporten"
discoveryUrl = "${MASKINPORTEN_WELL_KNOWN_URL}"

    [authProviders.requiredClaims]
    claims = ["scope=nav:arbeid:arbeidssokerregisteret.read"]

    [authProviders.optionalClaims]
    claims = ["aud", "sub", "nbf"]
