[[authProviders]]
name = "tokenx"
discoveryUrl = "http://localhost:8081/default/.well-known/openid-configuration"
tokenEndpointUrl = "http://localhost:8081/default/token"
clientId = "paw-microfrontend-toggler"

[authProviders.claims]
map = [ "acr=Level4", "acr=idporten-loa-high" ]
combineWithOr = true

[azureM2M]
tokenEndpointUrl = "http://localhost:8081/default/token"
clientId = "paw-microfrontend-toggler"

[kafka]
brokers = "localhost:9092"
applicationIdPrefix = "paw.paw-microfrontend-toggler"

[kafka.schemaRegistry]
url = "http://localhost:8082"

[kafkaProducer]
applicationIdSuffix = "producer-v1"

[kafkaStreams]
applicationIdSuffix = "stream-v1"
periodeTopic = "paw.arbeidssokerperioder-v1"
vedtakTopic = "pto.siste-14a-vedtak-v1"
microfrontendTopic = "min-side.aapen-microfrontend-v1"
toggleStoreName = "microfrontend-toggle"
varselStoreName = "microfrontend-varsel"
periodeToggleProcessor = "microfrontend-toggle-periode"
rapporteringToggleProcessor = "microfrontend-toggle-rapportering"

[kafkaKeys]
url = "http://localhost:8090/kafka-keys"
scope = "api://test.test.kafka-keys/.default"

[regler]
periodeTogglePunctuatorSchedule = "PT60S"
utsattDeaktiveringAvAiaMinSide = "PT10M"

[microfrontends]
aiaMinSide = "aia-min-side"
aiaBehovsvurdering = "aia-behovsvurdering"