betaVersion = false

[[authProviders]]
name = "tokenx"
discoveryUrl = "http://localhost:8081/default/.well-known/openid-configuration"
tokenEndpointUrl = "http://localhost:8081/default/token"
clientId = "paw-microfrontend-toggler"

[authProviders.requiredClaims]
map = ["acr=Level4", "acr=idporten-loa-high"]
combineWithOr = true

[azureM2M]
tokenEndpointUrl = "http://localhost:8081/default/token"
clientId = "paw-microfrontend-toggler"

[kafka]
brokers = "localhost:9092"
applicationIdPrefix = "paw.paw-microfrontend-toggler"

[kafka.schemaRegistry]
url = "http://localhost:8082"

[kafkaProducer]
toggleProducerIdSuffix = "toggle-producer-v1"

[kafkaStreams]
shutDownTimeout = "PT1S"
periodeStreamIdSuffix = "arbeidssokerperioder-stream-v1"
siste14aVedtakStreamIdSuffix = "siste-14a-vedtak-stream-v1"
periodeTopic = "paw.arbeidssokerperioder-v1"
rapporteringTopic = "paw.rapportering-v1"
beriket14aVedtakTopic = "paw.beriket-14a-vedtak-v1"
siste14aVedtakTopic = "pto.siste-14a-vedtak-v1"
microfrontendTopic = "min-side.aapen-microfrontend-v1"
periodeStoreName = "microfrontendTogglePeriodeStore"
siste14aVedtakPartitionCount = 1

[kafkaKeysClient]
url = "http://localhost:8090/kafka-keys"
scope = "api://test.test.kafka-keys/.default"

[regler]
periodeTogglePunctuatorSchedule = "PT60S"
utsattDeaktiveringAvAiaMinSide = "PT10M"

[microfrontends]
aiaMinSide = "aia-min-side"
aiaBehovsvurdering = "aia-behovsvurdering"
