[[authProviders]]
name = "tokenx"
audiences = ["paw-microfrontend-toggler"]
discoveryUrl = "http://localhost:8081/tokenx/.well-known/openid-configuration"

    [authProviders.requiredClaims]
    claims = ["acr=Level4", "acr=idporten-loa-high"]
    combineWithOr = true
