[[authProviders]]
name = "tokenx"
clientId = "paw-microfrontend-toggler"
discoveryUrl = "http://localhost:8081/tokenx/.well-known/openid-configuration"

    [authProviders.claims]
    map = ["acr=Level4", "acr=idporten-loa-high"]
    combineWithOr = true
