gruppeId = "paw.arbeidssoekerregisteret-eksternt-api-v2"
periodeTopic = "paw.arbeidssokerperioder-beta-v7"

[database]
host = "localhost"
port = "5432"
username = "admin"
password = "admin"
name = "arbeidssoekerregisteretapiekstern"