[[authProviders]]
name = "tokenx"
discoveryUrl = "http://localhost:8081/rapportering/.well-known/openid-configuration"
tokenEndpointUrl = "http://localhost:8081/rapportering/token"
clientId = "paw-rapportering-api"

[authProviders.claims]
map = [ "acr=Level4", "acr=idporten-loa-high" ]
combineWithOr = true

[[authProviders]]
name = "azure"
discoveryUrl = "http://localhost:8081/rapportering/.well-known/openid-configuration"
tokenEndpointUrl = "http://localhost:8081/rapportering/token"
clientId = "paw-rapportering-api"

[authProviders.claims]
map = [ "NAVident" ]
combineWithOr = false