global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /internal/metrics
    static_configs:
      - targets: [ "microfrontend-toggler:8080" ]
  - job_name: "tempo"
    static_configs:
      - targets: [ "tempo:3200" ]
