perioderGroupId = "${KAFKA_GROUP_ID_PERIODER}"
opplysningerGroupId = "${KAFKA_GROUP_ID_OPPLYSNINGER}"
profileringGroupId = "${KAFKA_GROUP_ID_PROFILERING}"
bekreftelseGroupId = "${KAFKA_GROUP_ID_BEKREFTELSE}"
perioderTopic = "${KAFKA_TOPIC_PERIODER}"
opplysningerTopic = "${KAFKA_TOPIC_OPPLYSNINGER}"
profileringTopic = "${KAFKA_TOPIC_PROFILERING}"
bekreftelseTopic = "${KAFKA_TOPIC_BEKREFTELSE}"

[[authProviders]]
name = "tokenx"
discoveryUrl = "${TOKEN_X_WELL_KNOWN_URL}"
tokenEndpointUrl = "${TOKEN_X_TOKEN_ENDPOINT}"
clientId = "${TOKEN_X_CLIENT_ID}"

    [authProviders.claims]
    map = ["acr=Level4", "acr=idporten-loa-high"]
    combineWithOr = true

[[authProviders]]
name = "azure"
discoveryUrl = "${AZURE_APP_WELL_KNOWN_URL}"
tokenEndpointUrl = "${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}"
clientId = "${AZURE_APP_CLIENT_ID}"

    [authProviders.claims]
    map = ["NAVident"]

[poaoClientConfig]
url = "${POAO_TILGANG_URL}"
scope = "${POAO_TILGANG_SCOPE}"

[database]
host = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_ARBEIDSSOEKERREGISTERETAPIOPPSLAG_HOST}"
port = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_ARBEIDSSOEKERREGISTERETAPIOPPSLAG_PORT}"
username = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_ARBEIDSSOEKERREGISTERETAPIOPPSLAG_USERNAME}"
password = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_ARBEIDSSOEKERREGISTERETAPIOPPSLAG_PASSWORD}"
name = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_API_OPPSLAG_ARBEIDSSOEKERREGISTERETAPIOPPSLAG_DATABASE}"
