[[authProviders]]
name = "tokenx"
audiences = ["paw-arbeidssoekerregisteret-api-oppslag"]
discoveryUrl = "http://localhost:8081/tokenx/.well-known/openid-configuration"

    [authProviders.requiredClaims]
    claims = ["acr=Level4", "acr=idporten-loa-high"]
    combineWithOr = true

[[authProviders]]
name = "azure"
audiences = ["paw-arbeidssoekerregisteret-api-oppslag"]
discoveryUrl = "http://localhost:8081/azure/.well-known/openid-configuration"

    [authProviders.requiredClaims]
    claims = ["NAVident"]
