name: Build, push, and deploy - paw-microfrontend-toggler

on:
  push:
    branches:
      - main
    paths:
      - 'apps/microfrontend-toggler/**'
      - '.github/workflows/microfrontend-toggler.yml'

env:
  IMAGE: europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/paw/paw-microfrontend-toggler
jobs:
  build:
    name: Build - paw-microfrontend-toggler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: set module to build
        run: echo "MODULE=:apps:microfrontend-toggler" >> $GITHUB_ENV
      - name: Set version
        run: echo "VERSION=$(date +'%y.%m.%d').${{ github.run_number }}-${{ github.run_attempt }}" >> $GITHUB_ENV
      - name: Login GAR
        uses: nais/login@v0
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: paw
      - name: Build and push image with Gradle
        id: docker-build-push
        working-directory: ./
        run: |
          echo "image=${{ env.IMAGE }}:${{ env.VERSION }}" >> $GITHUB_OUTPUT
          echo -Pversion=${{ env.VERSION }} -Pimage=${{ env.IMAGE }} ${{ env.MODULE }}:build ${{ env.MODULE }}:test ${{ env.MODULE }}:jib
          ./gradlew -Pversion=${{ env.VERSION }} -Pimage=${{ env.IMAGE }} ${{ env.MODULE }}:build ${{ env.MODULE }}:test ${{ env.MODULE }}:jib
          echo "DIGEST=$(cat ./apps/microfrontend-toggler/build/jib-image.digest)" >> $GITHUB_ENV
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
      - name: Attest and sign
        uses: nais/attest-sign@v1.3.4
        with:
          image_ref: ${{ env.IMAGE }}@${{ env.DIGEST }}
  deploy-dev:
    name: Deploy to dev-gcp - paw-microfrontend-toggler
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: ./apps/microfrontend-toggler/nais/nais-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}
#  deploy-prod:
#    if: github.ref == 'refs/heads/main'
#    name: Deploy to prod-gcp - paw-microfrontend-toggler
#    needs: build
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      id-token: write
#    steps:
#      - uses: actions/checkout@v4
#      - uses: nais/deploy/actions/deploy@v1
#        env:
#          TEAM: paw
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-gcp
#          RESOURCE: ./apps/microfrontend-toggler/nais/nais-prod.yaml
#          VAR: image=${{ needs.build.outputs.image }},env=prod,ingressDomain=intern.nav.no
