name: paw-aareg-client

on:
  push:
    branches:
      - main
    paths:
      - 'paw-aareg-client/**'

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Verify Gradle wrapper checksum
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle and Publish artifact
        working-directory: ./paw-aareg-client
        run: ./gradlew build test publish
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
